language: node_js
before_script:
  - npm install -g mocha
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  
deploy:
  provider: npm
  email: mujib517@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
